version: '3.3'
services:
  ic-webapp:
    container_name: ic-webapp
    image: 'ic-webapp:v1'
    environment:
      - ODOO_URL=odoo
      - PGADMIN_URL=pgadmin
    depends_on:
      - pgadmin
      - odoo
    networks:
      - ic-webapp
    ports:
        - '8080:8080'

  odoo:
    container_name: odoo
    image: 'odoo:13.0'
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - postgres
    networks:
      - ic-webapp
    ports:
        - '8069:8069'
    volumes:
      - '/data-odoo-compose:/var/lib/odoo/addons/13.0'
      - '/data-odoo-config-compose:/etc/odoo'
      - '/data-odoo-addons-compose:/mnt/extra-addons'

  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=abodojustin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_PORT=80
    networks:
      - ic-webapp
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - '/pgadmin-config-compose:/pgadmin4/servers.json'
      - '/pgadmin-data-compose:/var/tmp/pgadmin'

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    networks:
      - ic-webapp
    ports:
      - '5432:5432'
    volumes:
      - '/data-postgrey-compose:/var/lib/postgresql/data'

networks:
  ic-webapp:
    driver: bridge