apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  labels:
    app: odoo
spec:
  selector:
    app: odoo
    env: prod
  type: NodePort
  ports:
  - targetPort: 8069
    port: 8069
    nodePort: 30220
