apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
    env: prod
spec:
  selector:
    app: pgadmin
    env: prod
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30210
